apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bundle-app
  template:
    metadata:
      labels:
        app: bundle-app
    spec:
      containers:
      - name: go-backend
        image: konem/bundle:debug
        ports:
        - containerPort: 5000
      restartPolicy: Always
