apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bundle-db
  template:
    metadata:
      labels:
        app: bundle-db
    spec:
      containers:
      - name: bundle-postgres
        image: postgres:12.3-alpine
        ports:
        - containerPort: 5432
      restartPolicy: OnFailure
